# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/aaron/Project/P35_exercise4/Large_matrix_mult_IP/Large_matrix_mult_IP.cache/wt [current_project]
set_property parent.project_path /home/aaron/Project/P35_exercise4/Large_matrix_mult_IP/Large_matrix_mult_IP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/aaron/Project/P35_exercise4/Large_matrix_mult_IP/Large_matrix_mult_IP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/aaron/Project/P35_exercise4/src/multiplier.v
  /home/aaron/Project/P35_exercise4/src/Large_Matrix_mult.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Large_Matrix_Mult -part xc7z010clg400-1


write_checkpoint -force -noxdef Large_Matrix_Mult.dcp

catch { report_utilization -file Large_Matrix_Mult_utilization_synth.rpt -pb Large_Matrix_Mult_utilization_synth.pb }
